SELECT * FROM VEICULOS;

SELECT COUNT(*) AS TOTAL_VEICULOS FROM VEICULOS;

SELECT MARCA, MODELO FROM VEICULOS;

SELECT MARCA, MODELO FROM VEICULOS
WHERE MODELO = 'PAGANI';

SELECT MARCA, MODELO FROM VEICULOS
WHERE ID = 7;