CREATE TABLE ARTISTAS (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    MEMBROS INTEGER,
    GENERO_MUSICAL VARCHAR(50),
    PAIS_ORIGEM VARCHAR(50),
    ANO_INICIO INTEGER,
    MUSICA_MAIS_ESCUTADA VARCHAR(50),
    ATIVO BOOLEAN DEFAULT TRUE,

);

INSERT INTO ARTISTAS (
    NOME, TIPO , MEMBROS, GENERO_MUSICAL, PAIS_ORIGEM, ANO_INICIO, MUSICA_MAIS_ESCUTADA, ATIVO)
    
VALUES (
    'Mamonas Assassinas',
    'Banda',
    'Dinho, Bento Hinoto, Samuel Reoli, Sergio Reoli, Júlio Rasec',
    'Rock Cômico, Pop Rock',
    'Brasil',
     1995,
    'Pelados em Santos',
    'N'
);