CREATE TABLE ARTISTAS (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    MEMBROS INTEGER,
    GENERO_MUSICAL VARCHAR(50),
    PAIS_ORIGEM VARCHAR(50),
    ANO_INICIO INTEGER,
    MUSICA_MAIS_ESCUTADA VARCHAR(50),
    ATIVO BOOLEAN DEFAULT TRUE,

);