SELECT * FROM ARTISTAS;

SELECT COUNT(*) AS TOTAL_ARTISTAS FROM ARTISTAS;

SELECT NOME MUSICA_MAIS_ESCUTADA FROM ARTISTAS;

SELECT NOME MUSICA_MAIS_ESCUTADA FROM ARTISTAS
WHERE PAIS_ORIGEM = 'BRASIL';

SELECT NOME MUSICA_MAIS_ESCUTADA FROM ARTISTAS
WHERE ID = 3;