SELECT * FROM USUARIOS;

UPDATE USUARIOS SET USERNAME = 'ProGamer2025'
WHERE USERNAME = 'NoobMaster';

SELECT * FROM USUARIOS;

UPDATE USUARIOS SET PONTOS = PONTOS + 1000;

SELECT * FROM USUARIOS;

UPDATE USUARIOS SET EMAIL = 'main@gmail.com'
WHERE EMAIL = 'master@email.com';